enum ReportReasonEnum {
	BOT = "BOT",
	SPAM = "SPAM",
	DUPLICATE = "DUPLICATE",
	FALSE_INFO = "FALSE_INFO",
	HATE_SPEECH = "HATE_SPEECH",
	IMPERSONATION = "IMPERSONATION",
	INAPPROPRIATE = "INAPPROPRIATE",
	OTHER = "OTHER",
}

export default ReportReasonEnum;
